### ISSUE TITLE
Unable to install wapiti

### ISSUE THREAD

**Issue by mannyrayner** [mahmoud/wapiti#30]
I just tried to install wapitii (I appear to need it for the hazm package), but get an error:

$ pip install wapiti
Collecting wapiti
  Using cached https://files.pythonhosted.org/packages/94/e4/428658a281edc240281759a3b09b9ada60e56325a12c9492f13b97ecc394/wapiti-0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\cygwin64\\tmp\\pip-install-s0d_11cn\\wapiti\\setup.py'"'"'; __file__='"'"'C:\\cygwin64\\tmp\\pip-install-s0d_11cn\\wapiti\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\cygwin64\tmp\pip-install-s0d_11cn\wapiti\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\cygwin64\tmp\pip-install-s0d_11cn\wapiti\setup.py", line 28, in <module>
        raise NotImplementedError("wapiti Python 3 support en route to your location")
    NotImplementedError: wapiti Python 3 support en route to your location
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.1, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Can you advise?

Thank you,

Manny

**Comment by mahmoud** [comment]
Oh! Yes, wapiti hasn't seen a Python 3 update yet. It doesn't support Python 3. You might be able to get things working under Python 2. What's `hazm`?

I hadn't considered doing a wapiti python3 port, but it actually might be pretty interesting, I'll put it on the list!

**Comment by mannyrayner** [comment]
Thank you very much for the quick response! My bad, I see the Python 2.6/2.7 notice now.

hazm (https://github.com/sobhe/hazm) is a package for processing Persian text that I am trying to integrate into another platform. That's also supposed to run under 2.7, hopefully it will solve my problem.

**Comment by M1ha-Shvn** [comment]
Is this message still accurate? I see installation docs [here](https://github.com/wapiti-scanner/wapiti/blob/master/INSTALL.md) which tell that I should have python 3.9 and above. I install python3.11 virtualenv and... get this error. What version should I install?

**Comment by M1ha-Shvn** [comment]
Sorry, question closed. Didn't see `3` in installation guide `wapiti3` pip package.
